### ISSUE TITLE
Release Checklist for V1.1.1 patch release

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/enhanced-nft#129]
- [x] Close or defer all tickets in the epics (scope closure)
- [x]  Create release candidate branch (branching, tagging)
- [x]  Identify destination & distribution targets (communications, announcements)
- [x]  Ensure SRE pipelines are in place, including testing (testing evidence)
- [x]  Create readme in git repo (scope closure)
- [x] ensure changelog has been created
- [x]  Documentation updates are in place (docs team)

**Comment by cspramit** [comment]
Release can be closed @RitaMAllenCA

**Comment by RitaMAllenCA** [comment]
@cspramit 
Closed final issue for SDK v1.1.0 
Karan created release branch from dev
Karan created version bump (v1.1.1 for code; v1.1.0 for package) PR and included changelog and merged on new RC branch
Communicate to Bandy new release is out once posted as well as IPwe (let Mo know)
