### ISSUE TITLE
Release checklist for CEP78 v1.2

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/enhanced-nft#149]
- [x] (DEV) Close or defer all tickets in the epics (code complete/scope closure) - code freeze
- [x]  (DEV) Create release candidate branch (branching, tagging)
- [x]  (Business Owner) Identify destination & distribution targets (communications, announcements)
- [x]  (SRE) Ensure SRE pipelines are in place
- [x]  (DEV) unit & Integration tests have passed
- [x]  (DEV) Create readme in git repo (scope closure)
- [x]  (DEV) ensure changelog is in place
- [x]  (SRE) acceptance tests in a production environment has passed
- [x]  (DEV) Documentation updates are in place (docs team)
- [ ]

**Comment by cspramit** [comment]
Tagging & changelogs on Monday

**Comment by cspramit** [comment]
03/20 - Tagging and Changelogs done
